as-tree.zip:
  size: 118902
  object_id: 9278b11d-6536-470f-6f27-5b3cb2193fc5
  sha: sha256:adb3fa37c49bb137b772379a4c5e07c3ac9609871cd3058c376e32f9fb9ee434
bat.tar.gz:
  size: 3584928
  object_id: 9bc765d6-4e7e-4b34-6383-e73392a89af5
  sha: sha256:0dcd8ac79732c0d5b136f11f4ee00e581440e16a44eab5b3105b611bbf2cf191
fd.tar.gz:
  size: 1759301
  object_id: 689c8fba-01ec-4b17-7948-3b729e06b20e
  sha: sha256:2b6bfaae8c48f12050813c2ffe1884c61ea26e750d803df9c9114550a314cd14
fping.tar.gz:
  size: 195770
  object_id: c89aaefd-4c21-47e7-451c-4e53b65d48f5
  sha: sha256:be320771f075e47dd7e5704b485e9bdc7dd11107884345c0f7c18749357f668d
jq:
  size: 2255816
  object_id: bc111219-86df-435f-60b6-7beb123b64bb
  sha: sha256:020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d
ripgrep.tar.gz:
  size: 2263077
  object_id: a2513a08-56b8-4844-6067-901f15123996
  sha: sha256:1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599
yq:
  size: 11501752
  object_id: 4286bf85-5f4c-4c5e-6636-6ae3a340dbbd
  sha: sha256:be2c0ddcf426b6a231648610ec5d1666ae50e9f6473e82f6486f9f4cb6e3e2f7
