as-tree.zip:
  size: 118902
  object_id: 9278b11d-6536-470f-6f27-5b3cb2193fc5
  sha: sha256:adb3fa37c49bb137b772379a4c5e07c3ac9609871cd3058c376e32f9fb9ee434
bat.tar.gz:
  size: 3584928
  object_id: 9bc765d6-4e7e-4b34-6383-e73392a89af5
  sha: sha256:0dcd8ac79732c0d5b136f11f4ee00e581440e16a44eab5b3105b611bbf2cf191
fd.tar.gz:
  size: 1759301
  object_id: 689c8fba-01ec-4b17-7948-3b729e06b20e
  sha: sha256:2b6bfaae8c48f12050813c2ffe1884c61ea26e750d803df9c9114550a314cd14
fping.tar.gz:
  size: 215522
  object_id: b0b92358-42a0-46a3-511e-b4b4f0040876
  sha: sha256:15c4e32b6c55ff105bafe03e8c91c7ca1b2eda31bf9a7127326bb87887ee18fe
jq:
  size: 2255816
  object_id: bc111219-86df-435f-60b6-7beb123b64bb
  sha: sha256:020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d
ripgrep.tar.gz:
  size: 2263077
  object_id: a2513a08-56b8-4844-6067-901f15123996
  sha: sha256:1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599
yq:
  size: 13631672
  object_id: 207f924b-7962-47d3-6ebf-d4915f371c98
  sha: sha256:a74bd266990339e0c48a2103534aef692abf99f19390d12c2b0ce6830385c459
